/*
 * This source file was generated by the Gradle 'init' task
 */
package com.malfunctionz.malfunctionboard.nt;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
